from pathlib import Path
import json
R=Path(__file__).resolve().parents[1]
def icon(n):return '<span class="icon" style="--icon:url(../icons/'+n+'.svg)" aria-hidden="true"></span>'
def button(t,c='',a=''):return f'<button class="button {c}" {a}>{t}</button>'
def sample(h,b):return f'<article class="specimen"><h3>{h}</h3>{b}</article>'
items=[]
items.append(sample('Botón primario',button('Guardar compra')+button('Presionado','is-pressed')+button('En foco','is-focus')+button('No disponible','','disabled')+button(icon('loader-circle')+'Guardando…','','aria-busy="true" disabled')))
items.append(sample('Acciones secundarias',button('Volver','secondary')+button('Ver desglose','tertiary')+button('Eliminar','danger')+button(icon('plus'),'icon-only','aria-label="Agregar"')+'<p class="help">Eliminar abre confirmación. Iconos solos requieren nombre accesible.</p>'))
for name,label,value,attrs,help in [('text','Ingrediente','Harina de trigo','','Nombre persistente, no solo placeholder.'),('numeric','Cantidad comprada','1','inputmode="decimal"','Unidad siempre adyacente.'),('currency','Total pagado','42.00','inputmode="decimal"','MXN · Dos decimales al confirmar.'),('focus','En foco','Harina de trigo','class="is-focus"','Anillo 2px, separación 3px.'),('disabled','No disponible','Calculando…','disabled','Explicar por qué no está disponible.')]:
 items.append(sample(label,f'<div class="field"><label for="s-{name}">{label}</label><input id="s-{name}" value="{value}" {attrs}><p class="help">{help}</p></div>'))
items.append(sample('Validación en línea','<div class="field invalid"><label for="s-error">Total pagado</label><input id="s-error" value="0" aria-invalid="true" aria-describedby="s-message"><p id="s-message" class="error-text">'+icon('triangle-alert')+'Escribe un total mayor que $0.</p></div>'))
items.append(sample('Selección, fecha y hora','<div class="field"><label for="s-unit">Unidad</label><select id="s-unit"><option>kg</option><option>g</option><option>ml</option><option>piezas</option></select></div><div class="field"><label for="s-date">Fecha de entrega</label><input type="date" id="s-date" value="2026-09-18"></div><div class="field"><label for="s-time">Hora de entrega</label><input type="time" id="s-time" value="12:30"></div>'))
items.append(sample('Búsqueda','<div class="field"><label for="s-search">Buscar cliente</label><input id="s-search" type="search" placeholder="Nombre del cliente"></div>'))
items.append(sample('Cantidad por pasos','<div class="stepper">'+button(icon('minus'),'icon-only','aria-label="Quitar una pieza" data-step="-1"')+'<output id="step-value" aria-live="polite">12</output>'+button(icon('plus'),'icon-only','aria-label="Agregar una pieza" data-step="1"')+'</div><p class="help">Valor mínimo 1; eliminar línea es una acción distinta.</p>'))
items.append(sample('Estados de entrega','<div class="chips">'+''.join(f'<span class="chip {c}">{n}</span>' for n,c in [('Nuevo','neutral'),('Confirmado','info'),('En preparación','pending'),('Listo para entregar',''),('Entregado',''),('Cancelado','neutral')])+'</div>'))
items.append(sample('Estados de pago','<div class="chips"><span class="chip pending">Pendiente de cobro</span><span class="chip pending">Pago parcial</span><span class="chip">Pagado</span></div><p class="help">El color acompaña la etiqueta. Un saldo vigente no se pinta como error.</p>'))
items.append(sample('Opciones y pestañas','<div class="segments" aria-label="Escenario">'+''.join(f'<button aria-pressed="{str(i==0).lower()}" data-segment>{t}</button>' for i,t in enumerate(['×2','×2.5','×3','×3.5']))+'</div><div class="tabs" role="tablist"><button role="tab" aria-selected="true">Recetas</button><button role="tab" aria-selected="false">Productos</button></div>'))
items.append(sample('Resumen económico','<div class="computed"><span class="help">Costo por pieza</span><p class="money">$20.00 <small>MXN</small></p><div class="summary"><div><span class="help">Precio</span><p class="money">$40.00</p></div><div><span class="help">Ganancia</span><p class="money positive">$20.00</p></div></div><p class="help">Margen: 50.0% de la venta · Multiplicador ×2</p></div>'))
items.append(sample('Fila de pedido','<a class="row link" href="../prototypes/index.html#cobro"><div class="row-body"><strong>Ana · 12:30</strong><span class="help">12 roles de canela</span></div><span>Saldo $240</span>'+icon('chevron-right')+'</a>'))
items.append(sample('Imagen de receta','<img class="hero-img" src="../imagery/cinnamon-rolls-master.png" alt="Roles de canela sobre cerámica crema"><p class="help">350 × 180 CSS px; object-fit:cover; posición 65% 50%.</p>'))
items.append(sample('Sin fotografía','<div class="photo-placeholder">'+icon('image')+'<span>Sin foto</span></div><p class="help">No bloquea guardar ni altera el costo.</p>'))
items.append(sample('Sin registros','<div class="empty">'+icon('book-open')+'<h2>Tu primera receta</h2><p>Agrega ingredientes y cuántas piezas salen.</p><a class="button full" href="../prototypes/index.html#receta">Crear receta</a></div>'))
items.append(sample('Cargando','<div role="status"><p class="help">Cargando tus pedidos…</p><div aria-hidden="true"><div class="skeleton big"></div><div class="skeleton"></div><div class="skeleton"></div></div></div>'))
items.append(sample('Error global','<div class="notice error" role="alert">'+icon('wifi-off')+'<p>No se guardó la compra. Tus datos siguen aquí.</p></div>'+button('Reintentar','secondary full','data-retry')))
items.append(sample('Confirmación y aviso','<div class="notice success" role="status">'+icon('check')+'<p>Compra registrada.</p></div><div class="notice warning">'+icon('triangle-alert')+'<p>Falta el costo de un ingrediente. No podemos calcular el total.</p></div>'+button('Mostrar aviso','secondary','data-toast')))
items.append(sample('Hoja y diálogo',button('Editar cantidad','secondary','data-dialog="edit"')+button('Descartar cambios','danger','data-dialog="discard"')+'<p class="help">Foco dentro del diálogo, Escape y cierre explícito. El fondo no recibe interacción.</p>'))
nav='<nav class="navigation" style="position:static" aria-label="Muestra de navegación">'+''.join(f'<a href="../prototypes/index.html#{r}" '+('aria-current="page"' if r=='hoy' else '')+'>'+icon(i)+n+'</a>' for r,i,n in [('hoy','house','Hoy'),('pedidos','clipboard-list','Pedidos'),('recetario','book-open','Recetario'),('mas','ellipsis','Más')])+'</nav>'
items.append(sample('Navegación inferior',nav))
html='''<!doctype html><html lang="es-MX"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Componentes · EmprendimientoOS</title><link rel="stylesheet" href="../prototypes/styles.css"></head><body><main class="catalog"><a href="../brandbook/index.html">Volver al brandbook</a><h1 style="margin-top:16px">Componentes para trabajar con calma</h1><p>Valores reales de la dirección A. Los controles de esta página son muestras de diseño; no guardan datos de negocio.</p><div class="specimen-grid" style="margin-top:24px">'''+''.join(items)+'''</div></main><dialog id="demo" aria-labelledby="demo-title"><div class="dialog-body"><div class="dialog-head"><h2 id="demo-title"></h2><button class="button tertiary " aria-label="Cerrar" onclick="document.querySelector('#demo').close()">Cerrar</button></div><div id="demo-content"></div></div></dialog><div id="demo-toast" class="toast" role="status" hidden>Compra registrada en el ejemplo.</div><script>
const modal=document.querySelector('#demo');document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.step){let out=document.querySelector('#step-value');out.textContent=Math.max(1,Number(out.textContent)+Number(b.dataset.step))}if(b.hasAttribute('data-segment')){b.parentNode.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',x===b))}if(b.getAttribute('role')==='tab'){b.parentNode.querySelectorAll('button').forEach(x=>x.setAttribute('aria-selected',x===b))}if(b.hasAttribute('data-toast')||b.hasAttribute('data-retry')){const t=document.querySelector('#demo-toast');t.hidden=false;setTimeout(()=>t.hidden=true,5000)}if(b.dataset.dialog){document.querySelector('#demo-title').textContent=b.dataset.dialog==='edit'?'Editar cantidad':'¿Descartar cambios?';document.querySelector('#demo-content').innerHTML=b.dataset.dialog==='edit'?'<div class="field"><label for="dialog-number">Cantidad comprada</label><input id="dialog-number" inputmode="decimal" value="1"></div><button class="button full" onclick="this.closest(\\'dialog\\').close()">Aplicar al borrador</button>':'<p>Se perderán los cambios de esta captura. Los registros guardados no cambian.</p><div class="actions"><button class="button secondary full" onclick="this.closest(\\'dialog\\').close()">Seguir editando</button><button class="button danger full" onclick="this.closest(\\'dialog\\').close()">Descartar cambios</button></div>';modal.showModal()}});
</script></body></html>'''
(R/'components/index.html').write_text(html)
registry={
'button':{'size':'min-height 52; padding 12 16; gap 8; radius12','states':['default','pressed','focus','disabled','loading'],'variants':['primary','secondary','tertiary','destructive','icon'],'behavior':'submit stays visible; loading blocks duplicate activation; keep label; no disabling solely to hide validation'},
'input':{'size':'height52; padding12; radius12; border1; body16/24','states':['default','focus','disabled','error','readonly'],'types':['text','number','currency','quantity','select','date','time','search','textarea'],'error':'border2 danger; aria-invalid; describedby; first error focus; keep valid data'},
'quantity':{'size':'48 target; 8 gap; 28 minimum number width','states':['default','focus','disabled'],'behavior':'step=1 for piece quantities; minimum1; removing row requires explicit action'},
'card':{'size':'padding16; radius16; border1 line; no nested cards','states':['default'],'variants':['summary','recipe','order']},
'status':{'size':'14/20; padding4 10; radius999','states':['default'],'behavior':'semantic text always present; delivery and payment independent; use status-map.json'},
'chip-select':{'size':'min-height48 when interactive; display badge28 only noninteractive','states':['default','pressed','focus','disabled','selected']},
'segments':{'size':'padding4; gap4; target48; radius12','states':['default','focus','selected','disabled'],'behavior':'mutually exclusive scenarios; aria-pressed; arrows optional; no automatic price mutation'},
'bottom-nav':{'size':'height72+safeArea; four columns; label12/16; icon24','states':['default','focus','selected'],'behavior':'aria-current=page; active label+background; never icon alone'},
'sheet-dialog':{'size':'width min(480,100%); max-height85dvh; padding20; radius24; scrim #38291F66','states':['closed','open','loading','error'],'behavior':'native dialog/headless equivalent; trap focus; restore trigger; Escape close only non-destructive; dirty close opens discard confirmation'},
'toast':{'size':'max-width430; viewport gap16; padding14 16; radius12; bottom88+safeArea','states':['open','closed'],'behavior':'polite status; 6 seconds; no essential information solely transient; errors persistent'},
'empty':{'size':'padding40 16; icon40; title22/28','states':['no-data','no-results','no-history'],'behavior':'explain why and one relevant next action; never use dash as zero'},
'loading':{'size':'block110 or line20; radius8','states':['loading'],'behavior':'aria-busy region; status text; skeleton aria-hidden; static under reduced motion'},
'error-global':{'size':'padding12 14; radius12; icon24; text14/21','states':['network','server','permission','stale'],'behavior':'keep form; retry with idempotency; never claim saved before server'},
'money':{'size':'28/34 display; label14/20; tabular numbers','states':['known','unknown','zero','negative'],'behavior':'MXN explicit; 2dp amounts; 4+dp normalized cost; unknown dash plus cause; never silently zero'},
'image':{'size':'hero 100%x180; thumbnail104x64; border radius16','states':['available','missing','loading','failed'],'behavior':'cover position65% 50%; missing uses image icon+Sin foto; optional; no decorative photo in money errors'}
}
(R/'components/registry.json').write_text(json.dumps(registry,ensure_ascii=False,indent=2)+'\n')
statuses={'fulfillment':{'new':{'label':'Nuevo','tone':'neutral'},'confirmed':{'label':'Confirmado','tone':'info'},'in_preparation':{'label':'En preparación','tone':'warning'},'ready':{'label':'Listo para entregar','tone':'positive'},'delivered':{'label':'Entregado','tone':'positive'},'cancelled':{'label':'Cancelado','tone':'neutral'}},'payment':{'pending':{'label':'Pendiente de cobro','tone':'warning'},'partial':{'label':'Pago parcial','tone':'warning'},'paid':{'label':'Pagado','tone':'positive'}}}
(R/'components/status-map.json').write_text(json.dumps(statuses,ensure_ascii=False,indent=2)+'\n')
print(len(items),'visual specimen groups')
