from pathlib import Path
import json
R=Path(__file__).resolve().parents[1]
t=json.loads((R/'tokens/tokens.json').read_text());icons=json.loads((R/'icons/map.json').read_text())['icons']
def ic(n):return '<span class="icon" style="--icon:url(../icons/'+n+'.svg)" aria-hidden="true"></span>'
swatches=''.join(f'<div class="swatch"><div style="background:{v}"></div><p><strong>{k}</strong><br>{v}</p></div>' for k,v in t['color'].items() if k!='scrim')
types=''.join(f'<div class="row"><div class="row-body"><span style="font-family:var(--eo-font-{v[3]});font-size:{v[0]}px;line-height:{v[1]}px;font-weight:{v[2]}">'+('Tu cocina. Tu negocio.' if v[3]=='display' else 'Necesitas preparar 12 piezas')+f'</span><p class="help">{k} · {v[0]}/{v[1]} px · {v[2]}</p></div></div>' for k,v in t['type'].items())
iconshtml=''.join(f'<div class="icon-sample">{ic(n)}<strong>{label}</strong><code>{n}.svg</code></div>' for label,n in icons.items())
routes=[('hoy','Hoy','Preparar, entregar y cobrar'),('compra','Registrar compra','Hechos humanos y costo normalizado'),('receta','Receta','Ingredientes, rendimiento y versión'),('producto','Costos y precio','Ganancia, margen y escenarios'),('pedido','Tomar pedido','Cliente, productos y anticipo'),('cobro','Cobro y entrega','Dos estados independientes'),('produccion','Producción','Pedidos agrupados por fecha'),('historial','Antes y ahora','Economía con referencia histórica')]
links=''.join(f'<a href="../prototypes/index.html#{r}"><strong>{i+1:02d} · {n}</strong><small>{d}</small></a>' for i,(r,n,d) in enumerate(routes))
captures=''.join(f'<figure style="margin:0"><h3>{n}</h3><a href="../screens/evidence/{r}-390.png"><img src="../screens/evidence/{r}-390.png" alt="Referencia móvil: {n}" loading="lazy"></a></figure>' for r,n,d in routes)
html='''<!doctype html><html lang="es-MX"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EmprendimientoOS · Cocina cálida artesanal</title><link rel="icon" href="../assets/brand/favicon.ico"><link rel="stylesheet" href="../prototypes/styles.css"><style>.cover{display:grid;grid-template-columns:1.2fr 1fr;gap:32px;align-items:center;padding:32px 0 40px;border-bottom:1px solid var(--eo-line)}.cover img{width:100%;border-radius:16px}.cover h1{font-size:clamp(36px,5vw,56px);line-height:1.07;margin:16px 0}.cover p{max-width:55ch}.book-nav{display:flex;flex-wrap:wrap;gap:12px;margin:24px 0}.book-nav a{padding:12px;border:1px solid var(--eo-primary);border-radius:8px;text-decoration:none}.book-section{padding:24px 0;border-bottom:1px solid var(--eo-line)}.book-section>p{max-width:75ch;margin:12px 0}.brand-layout{display:grid;grid-template-columns:160px 1fr;gap:24px;align-items:center}.brand-layout img{max-width:100%}.brand-layout>div{min-width:0}.brand-layout>div>img{width:100%}.goodbad{display:grid;grid-template-columns:1fr 1fr;gap:16px}.goodbad article{padding:20px;border:1px solid var(--eo-line);border-radius:16px;background:white}.goodbad h3{margin-bottom:16px}.goodbad p{margin:8px 0}.space-row{display:flex;align-items:center;gap:16px;margin:8px 0}.space-row span{display:block;background:var(--eo-primary);height:16px}.screens-preview{height:520px;overflow:auto;border:1px solid var(--eo-line);border-radius:16px;background:white}.screens-preview img{width:100%}.screen-grid{grid-template-columns:repeat(auto-fit,minmax(min(280px,100%),1fr))}.screen-grid figure a{display:block;max-height:520px;overflow:auto;margin-top:12px}.splash{max-width:240px;max-height:480px;object-fit:contain}code{font-size:.875rem}footer{padding:32px 0}@media(max-width:700px){.cover,.goodbad{grid-template-columns:1fr}.cover img{max-height:260px;object-fit:cover}.brand-layout{grid-template-columns:80px 1fr}.book-nav a{flex:1;text-align:center}}</style></head><body><main class="catalog"><header class="cover"><div><p class="eyebrow">EmprendimientoOS · Brandbook v1.0</p><h1>Tu cocina.<br>Tu negocio.</h1><p>Cocina cálida artesanal: una identidad para trabajar con confianza, entender tus números y cuidar cada entrega.</p><p style="margin-top:20px"><span class="chip">A · Dirección aceptada</span></p><div class="actions"><a class="button" href="../prototypes/index.html#hoy">Recorrer la referencia móvil</a><a href="BRANDBOOK.md">Leer la especificación completa</a></div></div><img src="../imagery/cinnamon-rolls-master.png" alt="Roles de canela con luz natural sobre un plato crema"></header>
<nav class="book-nav" aria-label="Secciones del brandbook"><a href="#marca">Marca</a><a href="#color">Color</a><a href="#tipo">Tipografía</a><a href="#sistema">Sistema</a><a href="#iconos">Iconos</a><a href="#uso">Buen uso</a><a href="#pantallas">Pantallas</a><a href="#recursos">Recursos</a></nav>
<section class="book-section" id="marca"><p class="eyebrow">01 · Carácter</p><h2>Cálida, capaz y concreta.</h2><p>El trabajo abre la pantalla. La respuesta aparece antes del desglose. La persona registra lo que sabe; el sistema calcula y conserva la historia.</p><div class="brand-layout"><img src="../assets/brand/app-icon-192.png" alt="Monograma EO crema sobre cacao"><div><img src="../assets/brand/wordmark.svg" alt="EmprendimientoOS" style="max-width:400px"><p class="help">Wordmark DM Sans600 · monograma EO700 · área libre de media altura del contenedor. Nunca estirar ni añadir motivos decorativos.</p></div></div><p><a href="VOICE.md">Voz y tono</a> · <a href="microcopy.json">Textos de interfaz</a></p></section>
<section class="book-section" id="color"><p class="eyebrow">02 · Color con significado</p><h2>Crema, cacao, terracota y hierba.</h2><p>El rojo no convierte un saldo vigente en una urgencia. Los estados siempre se nombran. Los bordes de campos tienen más contraste que los separadores decorativos.</p><div class="swatches">'''+swatches+'''</div></section>
<section class="book-section" id="tipo"><p class="eyebrow">03 · Tipografía real</p><h2>Personalidad en el título. Claridad en la tarea.</h2><p>Fraunces600 para encabezados; DM Sans para interfaz. Las familias variables y sus licencias están incluidas. Tamaños en rem, sin impedir ampliación del texto.</p>'''+types+'''</section>
<section class="book-section" id="sistema"><p class="eyebrow">04 · Sistema de trabajo</p><h2>Medidas que se pueden implementar.</h2><div class="specimen-grid"><article class="specimen"><h3>Espacio</h3>'''+''.join(f'<div class="space-row"><code>{n:02d}px</code><span style="width:{max(n,1)}px"></span></div>' for n in t['space'])+'''</article><article class="specimen"><h3>Superficies y acción</h3><div class="card"><p class="help">Costo por pieza</p><p class="money">$20.00 <small>MXN</small></p></div><div class="actions"><button class="button">Guardar compra</button><button class="button secondary">Volver</button></div><p class="help" style="margin-top:12px">Tarjeta16 · control12 · foco2 + separación3 · objetivo48 · botón52.</p></article><article class="specimen"><h3>Responsive y movimiento</h3><p>320px:16 de margen.<br>390px:20 de margen.<br>Captura:max480.<br>Escritorio:max1120.</p><p class="help">Presionado80ms · estado160ms · hoja220ms. Con movimiento reducido, sin animación.</p><p><a href="../tokens/tokens.json">Tokens exactos</a></p></article></div><p><a class="button secondary" href="../components/index.html">Explorar componentes y estados</a></p></section>
<section class="book-section" id="iconos"><p class="eyebrow">05 · Iconografía</p><h2>Un significado, un símbolo.</h2><p>Lucide local, 24px, trazo de 2px. Los iconos acompañan etiquetas; los botones de icono tienen nombre accesible y área48px.</p><div class="icon-grid">'''+iconshtml+'''</div><p><a href="../icons/README.md">Fuente, versión, reglas y licencia</a></p></section>
<section class="book-section" id="uso"><p class="eyebrow">06 · Correcto e incorrecto</p><h2>La claridad cuida el negocio.</h2><div class="goodbad"><article><h3>Así sí</h3><div class="row"><div class="row-body"><strong>Ana · Entrega 12:30</strong><span class="help">Pago parcial</span></div><span>Saldo $240</span></div><p class="money">$0.0420 <small>por g</small></p><p class="help">El costo unitario conserva su precisión.</p><div class="notice error"><p>Escribe un total mayor que $0. Tus otros datos siguen aquí.</p></div></article><article><h3>Evitar</h3><p style="color:#bd654f">¡Ana te debe!</p><p class="money">$0.04 <small>por g</small></p><p class="help">El redondeo aparente pierde información.</p><div class="notice error"><p>Error. Vuelve a llenar todo.</p></div></article><article><h3>Magnitudes separadas</h3><div class="kv"><span>Por cobrar hoy</span><strong>$640</strong></div><div class="kv"><span>Ganancia estimada</span><strong>$480</strong></div><p class="help">El anticipo no se suma a la ganancia.</p></article><article><h3>Evitar equivalencias falsas</h3><p>×3 no significa margen 300%.</p><p>Cobrado no significa entregado.</p><p>Sin costo no significa costo $0.</p></article></div></section>
<section class="book-section" id="pantallas"><p class="eyebrow">07 · Ocho recorridos</p><h2>Del ingrediente al pedido cobrado.</h2><p>Referencias móviles en español, contratos de campos y estados. Los datos son ficticios y las interacciones no guardan información real.</p><div class="gallery-index">'''+links+'''</div><h2>Capturas del render final</h2><p class="help">Abre cada imagen para ver la captura completa. Las áreas de aquí permiten desplazar referencias largas.</p><div class="screen-grid">'''+captures+'''</div><p><a href="../screens/flows.json">Campos, transiciones y reglas de cada recorrido</a></p></section>
<section class="book-section" id="recursos"><p class="eyebrow">08 · Recursos y handoff</p><h2>Listo para una implementación acotada.</h2><div class="specimen-grid"><article class="specimen"><h3>App y PWA</h3><img src="../assets/brand/maskable-512.png" alt="Icono maskable" width="128" height="128"><p class="help">Maestro1024 · exports192/512 · maskable512 · Apple180 · favicon.</p><a href="../implementation-guide/manifest.example.json">Manifest de referencia</a></article><article class="specimen"><h3>Arranque</h3><img class="splash" src="../splashes/splash-standard-portrait.png" alt="Composición de arranque crema con EO y nombre"><p><a href="../splashes/README.md">Composición y matriz de exportación</a></p></article><article class="specimen"><h3>Para implementar</h3><p><a href="../implementation-guide/IMPLEMENTATION.md">Guía React/Tailwind/Inertia</a></p><p><a href="../implementation-guide/asset-manifest.json">Manifiesto de assets</a></p><p><a href="../implementation-guide/HANDOFF-CHECKLIST.md">Checklist de entrega</a></p><p><a href="../implementation-guide/design-qa.md">Verificación visual y límites</a></p></article></div></section><footer><p>EmprendimientoOS · Dirección A aceptada. Paquete de diseño; producción sin modificar.</p><a href="../README.md">Índice y estado de TSK-002</a></footer></main></body></html>'''
(R/'brandbook/index.html').write_text(html)
